public with sharing class AdditionDeductionConstant {

    // sobject name
    public static final String SOBJECT_NAME = 'Addition_Deduction__c';

     // field names
     public static final String FIELD_NAME_QUOTE = 'Quote__c';
     public static final String FIELD_NAME_AMOUNT = 'Amount__c';
     public static final String FIELD_NAME_PRODUCT_DETAILS = 'Details__c';
     public static final String FIELD_NAME_PRODUCT_TYPE = 'Type__c';


}