/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 04-08-2024
 * @last modified by  : Nilesh Badrakiya
**/

public with sharing class OpportunityConstants {

   // sobject name
   public static final String SOBJECT_NAME = 'Opportunity';
   
   // field names
   public static final String FIELD_NAME_CLOSEDATE = 'CloseDate';
   public static final String FIELD_NAME_OPPORTUNITY_NUMBER = 'Opportunity_Number__c';
   public static final String FIELD_NAME_ACCOUNT = 'AccountId';
   public static final String FIELD_NAME_BIDDATE = 'Bid_Date__c';
   public static final String FIELD_NAME_CONSULTINGENGINEER = 'Consulting_Engineer__c';
   public static final String FIELD_NAME_GENERALCONTRACTOR = 'General_Contractor__c';
   public static final String FIELD_NAME_SHIPPINGNAME = 'Shipping_Name__c';
   public static final String FIELD_NAME_ATTENTIONTO = 'Attention_to__c';
   public static final String FIELD_NAME_SYNCQUOTE = 'Sync_Quote__c';
   public static final String FIELD_NAME_APPLICATIONENGINEER = 'Application_Engineer__c';
}