/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-13-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class ProductConstant {
    
    public static final String SOBJECT_NAME = 'Product2';
	
	// field names
	public static final String FIELD_NAME_PRODUCT_CODE = 'ProductCode';
	public static final String FIELD_NAME_MIDWEST_GROUP_OFFICE = 'Midwest_Group_Office__c';
	public static final String FIELD_NAME_DESCRIPTION = 'Product_Description__c';
    public static final String FIELD_NAME_MANUFACTURER = 'Manufacturer__c';
    public static final String FIELD_NAME_FAMILY = 'Family';
    public static final String FIELD_NAME_WEIGHT = 'Weight__c';
    public static final String FIELD_NAME_PRODUCT_TYPE = 'Product_Type__c';
    public static final String FIELD_NAME_HIDE_PRODUCT = 'HideProduct__c';
	
    //constant
    public static final String CONSTANT_ASC = 'ASC';
    public static final String CONSTANT_DESC = 'DESC';

}