/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 03-14-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class ProductGroupConstants {
    
    // sobject name
    public static final String SOBJECT_NAME = 'Product_Group__c';

    // field names
    public static final String FIELD_NAME_QUOTE = 'Quote__c';
    public static final String FIELD_NAME_PARENT_PRODUCT_GROUP = 'Parent_Product_Group__c';
    public static final String FIELD_NAME_TOTAL_GROUP_EXTENDED_COST = 'Total_Group_Extended_Cost__c';
    public static final String FIELD_NAME_GRAND_QUANTITY_TOTAL = 'Grand_Quantity_Total__c';
    public static final String FIELD_NAME_TOTAL_SUB_GROUPS = 'Total_Sub_Groups__c';
    public static final String FIELD_NAME_TOTAL_EXTENDED_COST = 'Total_Extended_Cost__c';
    public static final String FIELD_NAME_QUANTITY_TOTAL = 'Quantity_Total__c';
    public static final String FIELD_NAME_TOTAL_LINE_ITEMS = 'Total_Line_Items__c';
    public static final String FIELD_NAME_INDEX = 'Index__c';
    public static final String FIELD_NAME_PAGE_BREAK = 'Page_Break__c';
    public static final String FIELD_NAME_HIDE_QUANTITY = 'Hide_Quantity__c';
    public static final String FIELD_NAME_HIDE_CODE = 'Hide_Code__c';
    public static final String FIELD_NAME_HIDE_AMOUNT = 'Hide_Amount__c';
    public static final String FIELD_NAME_HIDE_LINE = 'Hide_Line__c';
    public static final String FIELD_NAME_HIDE_PRICING = 'Hide_Pricing__c';
    public static final String FIELD_NAME_ALTERNATE = 'Alternate__c';

    // Constants
    public static final String CONSTANT_COUNT_VALUE = 'countValue';

}