/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 04-08-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class QuoteLineItemConstants {
    
    // sobject name
    public static final String SOBJECT_NAME = 'Product_Select__c';

    // field names
    public static final String FIELD_NAME_PRODUCT_GROUP = 'Product_Group__c';
    public static final String FIELD_NAME_SALE_TYPE = 'Sale_Type__c';
    public static final String FIELD_NAME_TAG = 'Tag__c';
    public static final String FIELD_NAME_PRODUCT_NAME = 'Product_Name__c';
    public static final String FIELD_NAME_PRODUCT_CODE = 'Product_Code__c';
    public static final String FIELD_NAME_QUANTITY = 'Quantity__c';
    public static final String FIELD_NAME_LIST_PRICE = 'List_Price__c';
    public static final String FIELD_NAME_MULTIPLIER = 'Multiplier__c';
    public static final String FIELD_NAME_UNIT_COST = 'Unit_Cost__c';
    public static final String FIELD_NAME_EXTENDED_COST = 'Extended_Cost__c';
    public static final String FIELD_NAME_MARGIN_PERCENTAGE = 'Margin_Percentage__c';
    public static final String FIELD_NAME_ALTERNATE = 'Alternate__c';
    public static final String FIELD_NAME_SALE_PRICE = 'Sales_Price__c';
    public static final String FIELD_NAME_CR = 'CR__c';
    public static final String FIELD_NAME_QUOTE = 'Quote__c';
    public static final String FIELD_NAME_ROW_INDEX = 'Row_Index__c';
    public static final String FIELD_NAME_DESCRIPTION = 'Descriptions__c';
    public static final String FIELD_NAME_PAGE_BREAK = 'Page_Break__c';
    public static final String FIELD_NAME_HIDE_QUANTITY = 'Hide_Quantity__c';
    public static final String FIELD_NAME_HIDE_CODE = 'Hide_Code__c';
    public static final String FIELD_NAME_HIDE_LINE = 'Hide_Line__c';
    public static final String FIELD_NAME_HIDE_PRICING = 'Hide_Pricing__c';
    public static final String FIELD_NAME_RELEASEPICK = 'Release_pick__c';
    public static final String FIELD_NAME_SALES_ORDER_LINE = 'Sales_Order_Line__c';
    public static final String FIELD_NAME_PRODUCTID = 'ProductId__c';

    // Constants
    public static final String CONSTANT_COUNT_VALUE = 'countValue';

}