/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-14-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class SalesOrderLineConstants {
    
    // sobject name
	public static final String SOBJECT_NAME = 'AcctSeedERP__Sales_Order_Line__c';
	
	// field names
	public static final String FIELD_NAME_QUOTE_LINE_ITEM = 'Quote_Line_Item__c';
    public static final String FIELD_NAME_DESCRIPTION = 'Description__c';


    //Relationship
}